# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Playstore Beta"
  lane :internal do
    gradle(
        task: "clean bundle",
        build_type: "release",
        print_command: false,
    )
    upload_to_play_store(track: 'internal')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
#   lane :version do
#     increment_build_number
#     increment_version_number(bump_type: "patch")
#   end
end
