name: Deploy on playstore
on:
  push:
    branches: [ main ]

jobs:
  # use fastlane to deploy the App
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install Fastlane
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # google-services.json is from the firebase console
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

      - name: Run Unit tests
        run: bundle exec fastlane test

      # the Keystore is the Play App Signing Key
      - name: Configure Keystore
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.KEYSTORE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.PLAY_STORE_KEY_PATH_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties

      # play_config.json is from the Google play console, it helps to deploy the app from the CI
      - name: Create Google Play Config file
        env:
          PLAY_CONFIG_JSON: ${{ secrets.GOOGLE_PLAY_API_AUTH }}
        run: |
          echo "$PLAY_CONFIG_JSON" > play_config.json

      - name: Deploy the app to Beta track 🚀
        run: bundle exec fastlane beta